### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by jakeobewell** [jakeobewell/Driving-Game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
user can see their car

- [x] Create an HTML page that links styles.css and main.js.
- [x] Create and img tag in the body of HTML and set "src" attribute to a top down view of a car.
- [x] Set img width in CSS.
