### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by jakeobewell** [jakeobewell/Driving-Game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] In HTML, create classes that will match direction of car.
- [x] In CSS, use classes to change direction that car is facing.
- [x] In JavaScript, create a function that will change car class name based on arrow key pushed.
- [x] add an event listener for keydown that calls the change direction function.
