### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by jakeobewell** [jakeobewell/Driving-Game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Make car position absolute.
- [x] create function that alters position of car on the page.
- [x] add listener so that car drive function is called when space bar is pressed.
- [x] set interval so that drive function is called repeatedly when space bar is pressed.
